const jobs = [
  {
    id: 'job-001', title: 'Residential Masonry Wall Construction', type: 'task-based',
    description: 'Build a 20-meter perimeter wall for a residential property in Malolos.',
    status: 'active', clientId: 'user-001', clientName: 'Juan Dela Cruz',
    budget: 25000, location: 'Malolos, Bulacan', category: 'Masonry',
    skills: ['Masonry', 'Tiling'],
    createdAt: '2025-04-10T08:00:00Z', deadline: '2025-06-15T17:00:00Z',
    proposalCount: 2, acceptedProposalId: 'prop-001', flags: 0, notes: [],
    tasks: [
      { id: 'task-001', name: 'Build 20m perimeter wall', status: 'in-progress', milestone: 'Wall framing' },
    ],
  },
  {
    id: 'job-002', title: 'Electrical Rewiring for Commercial Building', type: 'contractor-based',
    description: 'Complete electrical rewiring for a 3-storey commercial building in Meycauayan.',
    status: 'active', clientId: 'user-014', clientName: 'Carmen Torres',
    budget: 150000, location: 'Meycauayan, Bulacan', category: 'Electrical',
    skills: ['Electrical'],
    createdAt: '2025-04-20T10:00:00Z', deadline: '2025-07-01T17:00:00Z',
    proposalCount: 2, acceptedProposalId: 'prop-002', flags: 0, notes: [],
    tasks: [
      { id: 'task-002', name: 'Rough-in wiring installation', status: 'completed', milestone: 'Rough-in complete' },
      { id: 'task-003', name: 'Install breaker panels and subpanels', status: 'in-progress', milestone: 'Panel installation' },
      { id: 'task-004', name: 'Final connections and testing', status: 'pending', milestone: 'Final inspection' },
    ],
  },
  {
    id: 'job-003', title: 'Event Stage Setup for Barrio Fiesta', type: 'task-based',
    description: 'Setup and rigging for a stage at the annual Barrio Fiesta in Bocaue.',
    status: 'finished', clientId: 'user-019', clientName: 'Gloria Macapagal',
    budget: 45000, location: 'Bocaue, Bulacan', category: 'Event Setup',
    skills: ['Carpentry', 'Rigging', 'Event Setup'],
    createdAt: '2025-03-01T09:00:00Z', deadline: '2025-03-15T12:00:00Z',
    proposalCount: 1, acceptedProposalId: 'prop-003', flags: 0, notes: [],
    tasks: [
      { id: 'task-005', name: 'Stage setup and rigging', status: 'completed', milestone: 'Stage complete' },
    ],
  },
  {
    id: 'job-004', title: 'Plumbing Repair for Apartment Complex', type: 'task-based',
    description: 'Fix multiple leaking pipes and replace fittings for a 12-unit apartment.',
    status: 'active', clientId: 'user-006', clientName: 'Elena Villanueva',
    budget: 18000, location: 'Plaridel, Bulacan', category: 'Plumbing',
    skills: ['Plumbing'],
    createdAt: '2025-05-05T11:00:00Z', deadline: '2025-05-30T17:00:00Z',
    proposalCount: 2, acceptedProposalId: null, flags: 0, notes: [],
    tasks: [],
  },
  {
    id: 'job-005', title: 'Warehouse Welding and Metal Racks', type: 'contractor-based',
    description: 'Fabricate and install heavy-duty metal racks for a warehouse in San Jose Del Monte.',
    status: 'active', clientId: 'user-001', clientName: 'Juan Dela Cruz',
    budget: 85000, location: 'San Jose Del Monte, Bulacan', category: 'Welding',
    skills: ['Welding', 'Metal Fabrication'],
    createdAt: '2025-04-15T08:30:00Z', deadline: '2025-06-30T17:00:00Z',
    proposalCount: 1, acceptedProposalId: 'prop-004', flags: 1,
    notes: [{ author: 'admin-001', text: 'Client reported concerns about timeline', createdAt: '2025-05-18T14:00:00Z' }],
    tasks: [
      { id: 'task-006', name: 'Fabricate main support beams', status: 'completed', milestone: 'Fabrication complete' },
      { id: 'task-007', name: 'Install rack frames', status: 'in-progress', milestone: 'Frame installation' },
      { id: 'task-008', name: 'Weld cross-bracing and finish', status: 'pending', milestone: 'Final welding' },
    ],
  },
  {
    id: 'job-006', title: 'Carpentry Works for New Residential Home', type: 'contractor-based',
    description: 'Full carpentry for a 2-storey residential home including framing, cabinets, and trim.',
    status: 'flagged', clientId: 'user-014', clientName: 'Carmen Torres',
    budget: 200000, location: 'Santa Maria, Bulacan', category: 'Carpentry',
    skills: ['Carpentry'],
    createdAt: '2025-05-01T07:00:00Z', deadline: '2025-08-01T17:00:00Z',
    proposalCount: 1, acceptedProposalId: 'prop-005', flags: 2,
    notes: [{ author: 'support-001', text: 'Flagged for incomplete scope description', createdAt: '2025-05-10T09:00:00Z' }],
    tasks: [
      { id: 'task-009', name: 'Framing and structural work', status: 'pending', milestone: 'Framing' },
      { id: 'task-010', name: 'Cabinet installation', status: 'pending', milestone: 'Cabinetry' },
      { id: 'task-011', name: 'Trim and finishing', status: 'pending', milestone: 'Finishing' },
    ],
  },
  {
    id: 'job-007', title: 'Tiling for Commercial Space', type: 'task-based',
    description: 'Install floor and wall tiles for a small commercial space in Guiguinto.',
    status: 'finished', clientId: 'user-019', clientName: 'Gloria Macapagal',
    budget: 35000, location: 'Guiguinto, Bulacan', category: 'Tiling',
    skills: ['Tiling', 'Masonry'],
    createdAt: '2025-02-10T08:00:00Z', deadline: '2025-03-01T17:00:00Z',
    proposalCount: 1, acceptedProposalId: 'prop-006', flags: 0, notes: [],
    tasks: [
      { id: 'task-012', name: 'Install floor and wall tiles', status: 'completed', milestone: 'Tiling complete' },
    ],
  },
  {
    id: 'job-008', title: 'Rigging for Light Tower Installation', type: 'task-based',
    description: 'Rigging assistance for installing a 15m light tower at an events venue.',
    status: 'active', clientId: 'user-004', clientName: 'Ana Gonzales',
    budget: 12000, location: 'Bocaue, Bulacan', category: 'Rigging',
    skills: ['Rigging'],
    createdAt: '2025-05-10T13:00:00Z', deadline: '2025-05-25T17:00:00Z',
    proposalCount: 1, acceptedProposalId: null, flags: 0, notes: [],
    tasks: [],
  },
  {
    id: 'job-009', title: 'Emergency Electrical Repair', type: 'task-based',
    description: 'Emergency electrical repair after a power surge damaged wiring in a home.',
    status: 'active', clientId: 'user-004', clientName: 'Ana Gonzales',
    budget: 8000, location: 'Bocaue, Bulacan', category: 'Electrical',
    skills: ['Electrical'],
    createdAt: '2025-05-18T16:00:00Z', deadline: '2025-05-20T17:00:00Z',
    proposalCount: 0, acceptedProposalId: null, flags: 0, notes: [],
    tasks: [],
  },
  {
    id: 'job-010', title: 'Masonry and Plastering for Renovation', type: 'contractor-based',
    description: 'Complete masonry and plastering for a house renovation project.',
    status: 'removed', clientId: 'user-010', clientName: 'Sofia Ramirez',
    budget: 60000, location: 'Hagonoy, Bulacan', category: 'Masonry',
    skills: ['Masonry', 'Plastering'],
    createdAt: '2025-03-08T10:00:00Z', deadline: '2025-04-30T17:00:00Z',
    proposalCount: 2, acceptedProposalId: null, flags: 3,
    notes: [{ author: 'admin-001', text: 'Removed - account flagged as fraudulent', createdAt: '2025-03-12T09:00:00Z' }],
    tasks: [],
  },
  {
    id: 'job-011', title: 'Office Renovation - Masonry & Painting', type: 'contractor-based',
    description: 'Complete masonry repointing and interior painting for a 2-storey office building in Malolos.',
    status: 'finished', clientId: 'user-001', clientName: 'Juan Dela Cruz',
    budget: 95000, location: 'Malolos, Bulacan', category: 'Masonry',
    skills: ['Masonry', 'Painting'],
    createdAt: '2025-02-01T08:00:00Z', deadline: '2025-03-15T17:00:00Z',
    proposalCount: 1, acceptedProposalId: 'prop-009', flags: 0, notes: [],
    tasks: [
      { id: 'task-013', name: 'Repoint exterior brick wall', status: 'completed', milestone: 'Masonry done', payment: 25000 },
      { id: 'task-014', name: 'Patch interior wall cracks', status: 'completed', milestone: 'Patching done', payment: 12000 },
      { id: 'task-015', name: 'Prime and paint ground floor', status: 'completed', milestone: 'Ground floor done', payment: 28000 },
      { id: 'task-016', name: 'Prime and paint second floor', status: 'completed', milestone: 'Second floor done', payment: 30000 },
    ],
  },
];

export default jobs;
