const notifications = [
  {
    id: 'notif-001',
    type: 'verification_approved',
    title: 'Verification Approved',
    description: 'Maria Santos has been verified as a Talent.',
    timestamp: '2025-05-20T09:30:00Z',
    read: false,
    link: '/verifications',
    actorName: 'Miguel Santos',
  },
  {
    id: 'notif-002',
    type: 'verification_rejected',
    title: 'Verification Rejected',
    description: 'Juan Dela Cruz identity verification was rejected — invalid ID.',
    timestamp: '2025-05-20T08:15:00Z',
    read: false,
    link: '/verifications',
    actorName: 'Miguel Santos',
  },
  {
    id: 'notif-003',
    type: 'dispute_filed',
    title: 'New Dispute Filed',
    description: 'Damage report filed by Ana Torres against equipment rental.',
    timestamp: '2025-05-20T07:45:00Z',
    read: false,
    link: '/oversight',
    actorName: 'System',
  },
  {
    id: 'notif-004',
    type: 'appeal_forwarded',
    title: 'Appeal Forwarded',
    description: 'Appeal from Carlos Reyes forwarded for admin decision.',
    timestamp: '2025-05-19T16:20:00Z',
    read: false,
    link: '/oversight',
    actorName: 'Angela Cruz',
  },
  {
    id: 'notif-005',
    type: 'user_suspended',
    title: 'Account Suspended',
    description: 'Ramon Fernandez was suspended due to policy violation.',
    timestamp: '2025-05-19T14:00:00Z',
    read: true,
    link: '/users/user-010',
    actorName: 'Miguel Santos',
  },
  {
    id: 'notif-006',
    type: 'points_issued',
    title: 'Galaw Points Issued',
    description: '200 GP issued to Sofia Ramirez as compensation.',
    timestamp: '2025-05-19T11:30:00Z',
    read: true,
    link: '/galaw-points',
    actorName: 'Miguel Santos',
  },
  {
    id: 'notif-007',
    type: 'content_flagged',
    title: 'Job Flagged for Review',
    description: 'Job "Emergency Plumbing Repair" was flagged by a user.',
    timestamp: '2025-05-19T10:00:00Z',
    read: false,
    link: '/jobs/job-003',
    actorName: 'System',
  },
  {
    id: 'notif-008',
    type: 'moderation_decision',
    title: 'Moderation Decision Made',
    description: 'Review flagged on Miguel\'s profile was kept after review.',
    timestamp: '2025-05-18T15:45:00Z',
    read: true,
    link: '/oversight',
    actorName: 'Angela Cruz',
  },
  {
    id: 'notif-009',
    type: 'dispute_resolved',
    title: 'Dispute Resolved',
    description: 'Job dispute between Ana Torres and Juan Dela Cruz has been resolved.',
    timestamp: '2025-05-18T13:20:00Z',
    read: true,
    link: '/disputes/dispute-001',
    actorName: 'Miguel Santos',
  },
  {
    id: 'notif-010',
    type: 'user_reinstated',
    title: 'Account Reinstated',
    description: 'Ramon Fernandez account has been reinstated after appeal.',
    timestamp: '2025-05-18T09:00:00Z',
    read: false,
    link: '/users/user-010',
    actorName: 'Miguel Santos',
  },
  {
    id: 'notif-011',
    type: 'points_deducted',
    title: 'Galaw Points Deducted',
    description: '50 GP deducted from Carlo Mendoza — proposal penalty.',
    timestamp: '2025-05-17T16:30:00Z',
    read: true,
    link: '/galaw-points',
    actorName: 'Miguel Santos',
  },
  {
    id: 'notif-012',
    type: 'new_report',
    title: 'New Report Filed',
    description: 'Fraud report filed by Maria Santos against a listing.',
    timestamp: '2025-05-17T14:00:00Z',
    read: false,
    link: '/oversight',
    actorName: 'System',
  },
  {
    id: 'notif-013',
    type: 'appeal_decided',
    title: 'Appeal Decided',
    description: 'Appeal from Luzviminda Garcia — suspension extended.',
    timestamp: '2025-05-17T11:15:00Z',
    read: true,
    link: '/appeals/appeal-003',
    actorName: 'Miguel Santos',
  },
  {
    id: 'notif-014',
    type: 'job_completed',
    title: 'Job Completed',
    description: 'Job "Residential Masonry Wall Construction" marked as completed.',
    timestamp: '2025-05-16T17:00:00Z',
    read: true,
    link: '/jobs/job-001',
    actorName: 'System',
  },
  {
    id: 'notif-015',
    type: 'user_flagged',
    title: 'Account Flagged',
    description: 'Jose Rizal account flagged — multiple dispute reports.',
    timestamp: '2025-05-16T10:30:00Z',
    read: true,
    link: '/users/user-004',
    actorName: 'Angela Cruz',
  },
];

export default notifications;
