const proposals = [
  { id: 'prop-001', jobId: 'job-001', talentId: 'user-002', talentName: 'Maria Santos', amount: 22000, status: 'accepted', coverLetter: 'I have 5 years experience in masonry and tiling. I can complete this within 2 weeks.', submittedAt: '2025-04-12T09:00:00Z', galawPointsUsed: 50, completionStatus: null, proofOfCompletion: null },
  { id: 'prop-002', jobId: 'job-002', talentId: 'user-003', talentName: 'Pedro Reyes', amount: 135000, status: 'accepted', coverLetter: 'Licensed electrician with 10 years commercial experience.', submittedAt: '2025-04-22T11:00:00Z', galawPointsUsed: 50, completionStatus: 'in-progress', proofOfCompletion: null },
  { id: 'prop-003', jobId: 'job-003', talentId: 'user-020', talentName: 'Danilo Fernandez', amount: 40000, status: 'accepted', coverLetter: 'Experienced in stage setup for fiestas. Team of 3 available.', submittedAt: '2025-03-03T08:00:00Z', galawPointsUsed: 50, completionStatus: 'completed', proofOfCompletion: ['photo_001.jpg', 'photo_002.jpg'] },
  { id: 'prop-004', jobId: 'job-005', talentId: 'user-009', talentName: 'Antonio Flores', amount: 78000, status: 'accepted', coverLetter: 'Expert welder with 8 years experience in fabrication.', submittedAt: '2025-04-17T10:00:00Z', galawPointsUsed: 50, completionStatus: 'in-progress', proofOfCompletion: null },
  { id: 'prop-005', jobId: 'job-006', talentId: 'user-011', talentName: 'Jose Rizal III', amount: 180000, status: 'accepted', coverLetter: 'Master carpenter with portfolio of 20+ residential projects.', submittedAt: '2025-05-03T07:30:00Z', galawPointsUsed: 50, completionStatus: 'in-progress', proofOfCompletion: null },
  { id: 'prop-006', jobId: 'job-007', talentId: 'user-002', talentName: 'Maria Santos', amount: 32000, status: 'accepted', coverLetter: 'Available to start immediately. Quality tiling guaranteed.', submittedAt: '2025-02-12T09:00:00Z', galawPointsUsed: 50, completionStatus: 'completed', proofOfCompletion: ['tiling_final.jpg'] },
  { id: 'prop-007', jobId: 'job-001', talentId: 'user-020', talentName: 'Danilo Fernandez', amount: 24000, status: 'rejected', coverLetter: 'Can do this job within budget.', submittedAt: '2025-04-13T14:00:00Z', galawPointsUsed: 50, completionStatus: null, proofOfCompletion: null },
  { id: 'prop-008', jobId: 'job-002', talentId: 'user-009', talentName: 'Antonio Flores', amount: 140000, status: 'rejected', coverLetter: 'Experienced electrical contractor.', submittedAt: '2025-04-23T09:00:00Z', galawPointsUsed: 50, completionStatus: null, proofOfCompletion: null },
  { id: 'prop-009', jobId: 'job-011', talentId: 'user-011', talentName: 'Jose Rizal III', amount: 95000, status: 'accepted', coverLetter: 'Full-service masonry and painting contractor. Can handle the complete renovation.', submittedAt: '2025-02-03T09:00:00Z', galawPointsUsed: 50, completionStatus: 'completed', proofOfCompletion: ['renovation_before.jpg', 'renovation_after.jpg'] },
];

export default proposals;
