const questions = [
  {
    id: 'q-001', categoryId: 'cat-001',
    question: 'What type of mortar mix is recommended for load-bearing brick walls?',
    questionType: 'multiple_choice',
    options: ['Type M', 'Type N', 'Type S', 'Type O'],
    correctAnswer: 'Type S',
    difficulty: 'intermediate', points: 10, isActive: true,
    createdAt: '2025-01-15T08:00:00Z',
  },
  {
    id: 'q-002', categoryId: 'cat-001',
    question: 'A standard clay brick measures approximately:',
    questionType: 'multiple_choice',
    options: ['190 x 90 x 90 mm', '200 x 100 x 100 mm', '180 x 80 x 80 mm', '210 x 100 x 75 mm'],
    correctAnswer: '190 x 90 x 90 mm',
    difficulty: 'beginner', points: 5, isActive: true,
    createdAt: '2025-01-15T08:30:00Z',
  },
  {
    id: 'q-003', categoryId: 'cat-001',
    question: 'Reinforced concrete must be cured for at least 7 days.',
    questionType: 'true_false',
    options: ['True', 'False'],
    correctAnswer: 'True',
    difficulty: 'beginner', points: 5, isActive: true,
    createdAt: '2025-01-16T09:00:00Z',
  },
  {
    id: 'q-004', categoryId: 'cat-001',
    question: 'What is the purpose of a expansion joint in masonry walls?',
    questionType: 'multiple_choice',
    options: ['To allow thermal movement', 'To improve aesthetics', 'To reduce material cost', 'To increase load capacity'],
    correctAnswer: 'To allow thermal movement',
    difficulty: 'advanced', points: 15, isActive: true,
    createdAt: '2025-01-16T10:00:00Z',
  },
  {
    id: 'q-005', categoryId: 'cat-001',
    question: 'Describe the proper procedure for mixing concrete by hand on-site.',
    questionType: 'descriptive',
    options: [],
    correctAnswer: null,
    difficulty: 'intermediate', points: 20, isActive: true,
    createdAt: '2025-01-17T08:00:00Z',
  },
  {
    id: 'q-006', categoryId: 'cat-002',
    question: 'What is the standard voltage for residential electrical outlets in the Philippines?',
    questionType: 'multiple_choice',
    options: ['110V', '220V', '240V', '120V'],
    correctAnswer: '220V',
    difficulty: 'beginner', points: 5, isActive: true,
    createdAt: '2025-01-15T09:00:00Z',
  },
  {
    id: 'q-007', categoryId: 'cat-002',
    question: 'A circuit breaker is primarily used to protect against:',
    questionType: 'multiple_choice',
    options: ['Overcurrent and short circuits', 'Voltage spikes only', 'Power surges from lightning', 'Frequency fluctuations'],
    correctAnswer: 'Overcurrent and short circuits',
    difficulty: 'beginner', points: 5, isActive: true,
    createdAt: '2025-01-15T09:30:00Z',
  },
  {
    id: 'q-008', categoryId: 'cat-002',
    question: 'Ground Fault Circuit Interrupters (GFCI) are required in wet locations.',
    questionType: 'true_false',
    options: ['True', 'False'],
    correctAnswer: 'True',
    difficulty: 'intermediate', points: 10, isActive: true,
    createdAt: '2025-01-16T10:00:00Z',
  },
  {
    id: 'q-009', categoryId: 'cat-002',
    question: 'Explain how to properly size a wire for a given electrical load.',
    questionType: 'descriptive',
    options: [],
    correctAnswer: null,
    difficulty: 'advanced', points: 20, isActive: true,
    createdAt: '2025-01-17T11:00:00Z',
  },
  {
    id: 'q-010', categoryId: 'cat-003',
    question: 'What is the typical diameter of a standard residential water supply pipe?',
    questionType: 'multiple_choice',
    options: ['1/2 inch', '3/4 inch', '1 inch', '1 1/2 inch'],
    correctAnswer: '1/2 inch',
    difficulty: 'beginner', points: 5, isActive: true,
    createdAt: '2025-01-15T10:00:00Z',
  },
  {
    id: 'q-011', categoryId: 'cat-003',
    question: 'A P-trap under a sink is designed to:',
    questionType: 'multiple_choice',
    options: ['Prevent sewer gases from entering', 'Increase water pressure', 'Filter debris from wastewater', 'Reduce water consumption'],
    correctAnswer: 'Prevent sewer gases from entering',
    difficulty: 'intermediate', points: 10, isActive: true,
    createdAt: '2025-01-16T10:30:00Z',
  },
  {
    id: 'q-012', categoryId: 'cat-003',
    question: 'PVC pipes are suitable for hot water supply lines.',
    questionType: 'true_false',
    options: ['True', 'False'],
    correctAnswer: 'False',
    difficulty: 'intermediate', points: 10, isActive: true,
    createdAt: '2025-01-17T08:00:00Z',
  },
  {
    id: 'q-013', categoryId: 'cat-004',
    question: 'What is the most common type of wood used for framing in the Philippines?',
    questionType: 'multiple_choice',
    options: ['Mahogany', 'Narra', 'Pine', 'Yakal'],
    correctAnswer: 'Pine',
    difficulty: 'beginner', points: 5, isActive: true,
    createdAt: '2025-01-15T11:00:00Z',
  },
  {
    id: 'q-014', categoryId: 'cat-004',
    question: 'A rip cut is a cut made along the grain of the wood.',
    questionType: 'true_false',
    options: ['True', 'False'],
    correctAnswer: 'True',
    difficulty: 'beginner', points: 5, isActive: true,
    createdAt: '2025-01-15T11:30:00Z',
  },
  {
    id: 'q-015', categoryId: 'cat-004',
    question: 'What is the recommended angle for a circular saw blade when cross-cutting wood?',
    questionType: 'multiple_choice',
    options: ['0 degrees', '15 degrees', '45 degrees', '90 degrees'],
    correctAnswer: '0 degrees',
    difficulty: 'intermediate', points: 10, isActive: true,
    createdAt: '2025-01-16T11:00:00Z',
  },
  {
    id: 'q-016', categoryId: 'cat-004',
    question: 'Describe the steps to properly install a door jamb.',
    questionType: 'descriptive',
    options: [],
    correctAnswer: null,
    difficulty: 'advanced', points: 20, isActive: true,
    createdAt: '2025-01-17T09:00:00Z',
  },
  {
    id: 'q-017', categoryId: 'cat-005',
    question: 'What type of welding uses a consumable electrode coated in flux?',
    questionType: 'multiple_choice',
    options: ['SMAW (Stick)', 'TIG', 'MIG', 'Oxy-fuel'],
    correctAnswer: 'SMAW (Stick)',
    difficulty: 'beginner', points: 5, isActive: true,
    createdAt: '2025-02-01T08:00:00Z',
  },
  {
    id: 'q-018', categoryId: 'cat-005',
    question: 'What gas is commonly used as shielding gas in MIG welding?',
    questionType: 'multiple_choice',
    options: ['Argon', 'Oxygen', 'Nitrogen', 'Hydrogen'],
    correctAnswer: 'Argon',
    difficulty: 'intermediate', points: 10, isActive: true,
    createdAt: '2025-02-01T08:30:00Z',
  },
  {
    id: 'q-019', categoryId: 'cat-005',
    question: 'A fillet weld is used to join two pieces at a right angle.',
    questionType: 'true_false',
    options: ['True', 'False'],
    correctAnswer: 'True',
    difficulty: 'beginner', points: 5, isActive: true,
    createdAt: '2025-02-02T09:00:00Z',
  },
  {
    id: 'q-020', categoryId: 'cat-005',
    question: 'Explain the safety precautions required before performing arc welding.',
    questionType: 'descriptive',
    options: [],
    correctAnswer: null,
    difficulty: 'intermediate', points: 20, isActive: true,
    createdAt: '2025-02-03T10:00:00Z',
  },
  {
    id: 'q-021', categoryId: 'cat-006',
    question: 'What tool is used to cut ceramic tiles cleanly?',
    questionType: 'multiple_choice',
    options: ['Tile cutter', 'Circular saw', 'Hacksaw', 'Jigsaw'],
    correctAnswer: 'Tile cutter',
    difficulty: 'beginner', points: 5, isActive: true,
    createdAt: '2025-02-05T08:00:00Z',
  },
  {
    id: 'q-022', categoryId: 'cat-006',
    question: 'What is the recommended gap for tile joints on floor installations?',
    questionType: 'multiple_choice',
    options: ['2-3 mm', '5-6 mm', '8-10 mm', 'No gap'],
    correctAnswer: '2-3 mm',
    difficulty: 'intermediate', points: 10, isActive: true,
    createdAt: '2025-02-05T08:30:00Z',
  },
  {
    id: 'q-023', categoryId: 'cat-006',
    question: 'Thinset mortar must be mixed to the consistency of peanut butter.',
    questionType: 'true_false',
    options: ['True', 'False'],
    correctAnswer: 'True',
    difficulty: 'beginner', points: 5, isActive: true,
    createdAt: '2025-02-06T09:00:00Z',
  },
  {
    id: 'q-024', categoryId: 'cat-006',
    question: 'Describe the process of waterproofing a bathroom floor before tiling.',
    questionType: 'descriptive',
    options: [],
    correctAnswer: null,
    difficulty: 'advanced', points: 20, isActive: true,
    createdAt: '2025-02-07T10:00:00Z',
  },
  {
    id: 'q-025', categoryId: 'cat-007',
    question: 'What is the safe working load (SWL) of a 1/2 inch diameter wire rope?',
    questionType: 'multiple_choice',
    options: ['Approx. 2 tons', 'Approx. 5 tons', 'Approx. 1 ton', 'Approx. 10 tons'],
    correctAnswer: 'Approx. 2 tons',
    difficulty: 'advanced', points: 15, isActive: true,
    createdAt: '2025-02-10T08:00:00Z',
  },
  {
    id: 'q-026', categoryId: 'cat-007',
    question: 'A bowline knot is used for creating a fixed loop at the end of a rope.',
    questionType: 'true_false',
    options: ['True', 'False'],
    correctAnswer: 'True',
    difficulty: 'intermediate', points: 10, isActive: true,
    createdAt: '2025-02-10T09:00:00Z',
  },
  {
    id: 'q-027', categoryId: 'cat-007',
    question: 'What is the minimum number of wraps for slings when lifting a load?',
    questionType: 'multiple_choice',
    options: ['1 full wrap', '2 full wraps', '3 full wraps', 'Depends on load weight'],
    correctAnswer: '2 full wraps',
    difficulty: 'intermediate', points: 10, isActive: true,
    createdAt: '2025-02-11T08:00:00Z',
  },
  {
    id: 'q-028', categoryId: 'cat-008',
    question: 'What is the maximum allowable weight for a single person to lift manually?',
    questionType: 'multiple_choice',
    options: ['25 kg', '50 kg', '75 kg', '100 kg'],
    correctAnswer: '25 kg',
    difficulty: 'beginner', points: 5, isActive: true,
    createdAt: '2025-02-15T08:00:00Z',
  },
  {
    id: 'q-029', categoryId: 'cat-008',
    question: 'Stage platforms should be secured with locking casters when in use.',
    questionType: 'true_false',
    options: ['True', 'False'],
    correctAnswer: 'True',
    difficulty: 'beginner', points: 5, isActive: true,
    createdAt: '2025-02-15T09:00:00Z',
  },
  {
    id: 'q-030', categoryId: 'cat-008',
    question: 'Describe the steps to safely set up a portable stage for an outdoor event.',
    questionType: 'descriptive',
    options: [],
    correctAnswer: null,
    difficulty: 'intermediate', points: 20, isActive: true,
    createdAt: '2025-02-16T10:00:00Z',
  },
];

export default questions;
