const reports = [
  { id: 'rpt-001', type: 'content_report', reporterId: 'user-011', reporterName: 'Jose Rizal III', targetType: 'job', targetId: 'job-006', title: 'Misleading job scope', description: 'Job scope does not match actual requirements.', severity: 'medium', status: 'resolved', createdAt: '2025-05-10T09:00:00Z', resolvedAt: '2025-05-12T14:00:00Z', decision: 'keep', decisionNotes: 'Client updated scope' },
  { id: 'rpt-002', type: 'user_report', reporterId: 'user-002', reporterName: 'Maria Santos', targetType: 'user', targetId: 'user-005', title: 'Harassment on job site', description: 'User made inappropriate comments.', severity: 'high', status: 'under-review', createdAt: '2025-05-15T16:00:00Z', resolvedAt: null, decision: null, decisionNotes: null },
  { id: 'rpt-003', type: 'content_report', reporterId: 'user-003', reporterName: 'Pedro Reyes', targetType: 'listing', targetId: 'list-004', title: 'Unsafe equipment listing', description: 'Generator listing does not have proper safety certifications.', severity: 'high', status: 'under-review', createdAt: '2025-05-05T09:00:00Z', resolvedAt: null, decision: null, decisionNotes: null },
  { id: 'rpt-004', type: 'content_report', reporterId: 'admin-001', reporterName: 'Miguel Santos', targetType: 'listing', targetId: 'list-008', title: 'Safety compliance violation', description: 'Forklift listing does not meet safety standards.', severity: 'critical', status: 'resolved', createdAt: '2025-02-15T10:00:00Z', resolvedAt: '2025-03-01T10:00:00Z', decision: 'remove', decisionNotes: 'Listing removed. Owner notified.' },
  { id: 'rpt-005', type: 'user_report', reporterId: 'user-014', reporterName: 'Carmen Torres', targetType: 'user', targetId: 'user-015', title: 'Repeated no-shows', description: 'Worker failed to show up for 3 scheduled jobs.', severity: 'medium', status: 'resolved', createdAt: '2025-03-20T08:00:00Z', resolvedAt: '2025-04-01T11:00:00Z', decision: 'warn', decisionNotes: 'Final warning issued. Account deleted after further violation.' },
  { id: 'rpt-006', type: 'content_report', reporterId: 'user-005', reporterName: 'Carlos Mendoza', targetType: 'review', targetId: 'rev-003', title: 'Fake review', description: 'This review appears to be from a fake account.', severity: 'low', status: 'pending', createdAt: '2025-05-18T14:00:00Z', resolvedAt: null, decision: null, decisionNotes: null },
];

export default reports;
