const userIncidents = [
  {
    id: 'inc-usr-001',
    title: 'Talent matched to job — Residential Masonry Wall Construction',
    type: 'match',
    severity: 'low',
    status: 'resolved',
    module: 'Jobs',
    description: 'Maria Santos (talent) was matched to Juan Dela Cruz\'s masonry job. Proposal of ₱22,000 accepted. Job is in progress.',
    reporter: 'System',
    respondentName: 'Maria Santos',
    assignedTo: null,
    assignedName: null,
    resolution: 'Match completed successfully. Job ongoing.',
    resolvedAt: '2025-04-13T10:00:00Z',
    timeline: [
      { date: '2025-04-10T08:00:00Z', title: 'Job posted by Juan Dela Cruz', actor: 'Juan Dela Cruz' },
      { date: '2025-04-12T09:00:00Z', title: 'Maria Santos submitted proposal', actor: 'Maria Santos' },
      { date: '2025-04-13T10:00:00Z', title: 'Proposal accepted — talent matched', actor: 'Juan Dela Cruz' },
    ],
    createdAt: '2025-04-13T10:00:00Z',
    updatedAt: '2025-04-13T10:00:00Z',
    notes: [],
  },
  {
    id: 'inc-usr-002',
    title: 'Talent matched to job — Electrical Rewiring for Commercial Building',
    type: 'match',
    severity: 'low',
    status: 'resolved',
    module: 'Jobs',
    description: 'Pedro Reyes (talent) was matched to Carmen Torres\'s electrical rewiring job. Proposal of ₱135,000 accepted.',
    reporter: 'System',
    respondentName: 'Pedro Reyes',
    assignedTo: null,
    assignedName: null,
    resolution: 'Match completed. Job in progress.',
    resolvedAt: '2025-04-23T12:00:00Z',
    timeline: [
      { date: '2025-04-20T10:00:00Z', title: 'Job posted by Carmen Torres', actor: 'Carmen Torres' },
      { date: '2025-04-22T11:00:00Z', title: 'Pedro Reyes submitted proposal', actor: 'Pedro Reyes' },
      { date: '2025-04-23T12:00:00Z', title: 'Proposal accepted — talent matched', actor: 'Carmen Torres' },
    ],
    createdAt: '2025-04-23T12:00:00Z',
    updatedAt: '2025-04-23T12:00:00Z',
    notes: [],
  },
  {
    id: 'inc-usr-003',
    title: 'Carlos Mendoza suspended — repeated no-shows',
    type: 'violation',
    severity: 'high',
    status: 'resolved',
    module: 'Users',
    description: 'Talent Carlos Mendoza failed to show up for 3 confirmed jobs in the past month. Clients filed complaints. Account suspended pending review.',
    reporter: 'Support Team',
    respondentName: 'Carlos Mendoza',
    assignedTo: 'admin-001',
    assignedName: 'Miguel Santos',
    resolution: 'Suspension upheld. User notified via email. Account will be reviewed after 30 days.',
    resolvedAt: '2025-05-20T14:00:00Z',
    timeline: [
      { date: '2025-05-10T08:00:00Z', title: 'First no-show complaint received', actor: 'Client' },
      { date: '2025-05-15T09:00:00Z', title: 'Second no-show complaint received', actor: 'Client' },
      { date: '2025-05-18T10:00:00Z', title: 'Third complaint — escalation triggered', actor: 'System' },
      { date: '2025-05-19T11:00:00Z', title: 'Incident assigned to Miguel Santos', actor: 'System' },
      { date: '2025-05-20T14:00:00Z', title: 'Account suspended', actor: 'Miguel Santos' },
    ],
    createdAt: '2025-05-18T10:00:00Z',
    updatedAt: '2025-05-20T14:00:00Z',
    notes: [
      { author: 'admin-001', text: 'User contacted support claiming medical emergency. No proof provided.', createdAt: '2025-05-20T15:00:00Z' },
    ],
  },
  {
    id: 'inc-usr-004',
    title: 'Sofia Ramirez flagged as fraudulent account',
    type: 'fraud',
    severity: 'critical',
    status: 'resolved',
    module: 'Verifications',
    description: 'Newly registered client Sofia Ramirez flagged by verification system. Submitted ID appears to be digitally altered. Account put on hold.',
    reporter: 'Verification System',
    respondentName: 'Sofia Ramirez',
    assignedTo: 'admin-001',
    assignedName: 'Miguel Santos',
    resolution: 'Account rejected and deleted. Submitted documents flagged as fraudulent.',
    resolvedAt: '2025-03-12T09:00:00Z',
    timeline: [
      { date: '2025-03-10T12:00:00Z', title: 'Account registered', actor: 'Sofia Ramirez' },
      { date: '2025-03-10T12:05:00Z', title: 'ID submitted for verification', actor: 'Sofia Ramirez' },
      { date: '2025-03-11T08:00:00Z', title: 'Verification system flagged ID as tampered', actor: 'System' },
      { date: '2025-03-11T09:00:00Z', title: 'Incident assigned to Miguel Santos', actor: 'System' },
      { date: '2025-03-12T09:00:00Z', title: 'Account rejected and deleted', actor: 'Miguel Santos' },
    ],
    createdAt: '2025-03-11T08:00:00Z',
    updatedAt: '2025-03-12T09:00:00Z',
    notes: [
      { author: 'admin-001', text: 'Obvious Photoshop artifacts on government ID. Flagged in fraud database.', createdAt: '2025-03-12T09:05:00Z' },
    ],
  },
  {
    id: 'inc-usr-005',
    title: 'Equipment damage reported — concrete mixer malfunction',
    type: 'damage',
    severity: 'high',
    status: 'investigating',
    module: 'Rentals',
    description: 'Ana Gonzales (equipment owner) reported that Pedro Reyes returned a concrete mixer with a damaged engine. Rental period was 3 days.',
    reporter: 'Ana Gonzales',
    respondentName: 'Pedro Reyes',
    assignedTo: 'admin-001',
    assignedName: 'Miguel Santos',
    resolution: null,
    resolvedAt: null,
    timeline: [
      { date: '2025-05-08T10:00:00Z', title: 'Equipment rented by Pedro Reyes', actor: 'System' },
      { date: '2025-05-11T16:00:00Z', title: 'Equipment returned — damage noted', actor: 'Ana Gonzales' },
      { date: '2025-05-11T17:00:00Z', title: 'Damage report filed', actor: 'Ana Gonzales' },
      { date: '2025-05-12T09:00:00Z', title: 'Incident assigned to Miguel Santos', actor: 'System' },
    ],
    createdAt: '2025-05-11T17:00:00Z',
    updatedAt: '2025-05-12T09:00:00Z',
    notes: [
      { author: 'admin-001', text: 'Awaiting repair quote from authorized mechanic.', createdAt: '2025-05-12T10:00:00Z' },
    ],
  },
  {
    id: 'inc-usr-006',
    title: 'Incomplete work dispute — Danilo Fernandez vs Gloria Macapagal',
    type: 'incomplete',
    severity: 'medium',
    status: 'resolved',
    module: 'Jobs',
    description: 'Client Gloria Macapagal reported that Danilo Fernandez did not complete the Event Stage Setup. Only 70% of the stage was built.',
    reporter: 'Gloria Macapagal',
    respondentName: 'Danilo Fernandez',
    assignedTo: 'admin-001',
    assignedName: 'Miguel Santos',
    resolution: 'Partial payment released. Danilo Fernandez penalized 500 GP. Warning issued.',
    resolvedAt: '2025-03-18T14:00:00Z',
    timeline: [
      { date: '2025-03-01T09:00:00Z', title: 'Job posted by Gloria Macapagal', actor: 'Gloria Macapagal' },
      { date: '2025-03-03T08:00:00Z', title: 'Danilo Fernandez matched to job', actor: 'Gloria Macapagal' },
      { date: '2025-03-15T12:00:00Z', title: 'Event date — incomplete stage noted', actor: 'Gloria Macapagal' },
      { date: '2025-03-16T10:00:00Z', title: 'Complaint filed', actor: 'Gloria Macapagal' },
      { date: '2025-03-18T14:00:00Z', title: 'Resolution issued', actor: 'Miguel Santos' },
    ],
    createdAt: '2025-03-16T10:00:00Z',
    updatedAt: '2025-03-18T14:00:00Z',
    notes: [
      { author: 'admin-001', text: 'Danilo claimed equipment failure. Insufficient evidence.', createdAt: '2025-03-18T14:05:00Z' },
    ],
  },
  {
    id: 'inc-usr-007',
    title: 'Escalated budget dispute — Carmen Torres vs Jose Rizal III',
    type: 'escalation',
    severity: 'medium',
    status: 'investigating',
    module: 'Jobs',
    description: 'Budget disagreement on Carpentry Works project. Client Carmen Torres claims work does not justify the ₱180,000 agreed price. Contractor Jose Rizal III disputes.',
    reporter: 'Carmen Torres',
    respondentName: 'Jose Rizal III',
    assignedTo: 'admin-001',
    assignedName: 'Miguel Santos',
    resolution: null,
    resolvedAt: null,
    timeline: [
      { date: '2025-05-01T07:00:00Z', title: 'Job posted by Carmen Torres', actor: 'Carmen Torres' },
      { date: '2025-05-03T07:30:00Z', title: 'Jose Rizal III matched to job', actor: 'Carmen Torres' },
      { date: '2025-05-10T09:00:00Z', title: 'Progress dispute flagged', actor: 'Carmen Torres' },
      { date: '2025-05-12T10:00:00Z', title: 'Incident escalated to admin', actor: 'Support' },
    ],
    createdAt: '2025-05-12T10:00:00Z',
    updatedAt: '2025-05-12T10:00:00Z',
    notes: [
      { author: 'admin-001', text: 'Need to review milestone deliverables before making a decision.', createdAt: '2025-05-12T11:00:00Z' },
    ],
  },
  {
    id: 'inc-usr-008',
    title: 'Antonio Flores posted prohibited content on job listing',
    type: 'violation',
    severity: 'medium',
    status: 'resolved',
    module: 'Listings',
    description: 'Talent Antonio Flores posted contact details (phone number) in a proposal, violating platform policy. Content removed.',
    reporter: 'System Moderator',
    respondentName: 'Antonio Flores',
    assignedTo: 'support-001',
    assignedName: 'Angela Cruz',
    resolution: 'Proposal edited. Warning issued to user. Repeated violations will result in suspension.',
    resolvedAt: '2025-05-08T15:00:00Z',
    timeline: [
      { date: '2025-05-07T14:00:00Z', title: 'Proposal submitted with contact details', actor: 'Antonio Flores' },
      { date: '2025-05-07T14:30:00Z', title: 'Auto-flagged by moderation system', actor: 'System' },
      { date: '2025-05-08T09:00:00Z', title: 'Incident assigned to Angela Cruz', actor: 'System' },
      { date: '2025-05-08T15:00:00Z', title: 'Content removed and warning issued', actor: 'Angela Cruz' },
    ],
    createdAt: '2025-05-07T14:30:00Z',
    updatedAt: '2025-05-08T15:00:00Z',
    notes: [],
  },
  {
    id: 'inc-usr-009',
    title: 'Job posting removed — fraudulent account',
    type: 'fraud',
    severity: 'critical',
    status: 'resolved',
    module: 'Jobs',
    description: 'Job posting "Masonry and Plastering for Renovation" by Sofia Ramirez was flagged and removed. Account previously flagged as fraudulent.',
    reporter: 'System',
    respondentName: 'Sofia Ramirez',
    assignedTo: 'admin-001',
    assignedName: 'Miguel Santos',
    resolution: 'Job removed. Account already deleted due to prior fraud detection.',
    resolvedAt: '2025-03-12T09:00:00Z',
    timeline: [
      { date: '2025-03-08T10:00:00Z', title: 'Job posted by Sofia Ramirez', actor: 'Sofia Ramirez' },
      { date: '2025-03-10T08:00:00Z', title: 'Job flagged by community', actor: 'Users' },
      { date: '2025-03-11T09:00:00Z', title: 'Investigation started', actor: 'Miguel Santos' },
      { date: '2025-03-12T09:00:00Z', title: 'Job removed and account deleted', actor: 'Miguel Santos' },
    ],
    createdAt: '2025-03-10T08:00:00Z',
    updatedAt: '2025-03-12T09:00:00Z',
    notes: [],
  },
  {
    id: 'inc-usr-010',
    title: 'Inappropriate review flagged — Pedro Reyes vs Ana Gonzales',
    type: 'violation',
    severity: 'low',
    status: 'open',
    module: 'Moderation',
    description: 'Review from Pedro Reyes about Ana Gonzales (equipment owner) contains offensive language and unsubstantiated claims. Awaiting moderation decision.',
    reporter: 'System Moderator',
    respondentName: 'Pedro Reyes',
    assignedTo: null,
    assignedName: null,
    resolution: null,
    resolvedAt: null,
    timeline: [
      { date: '2025-04-09T08:00:00Z', title: 'Review submitted by Pedro Reyes', actor: 'Pedro Reyes' },
      { date: '2025-04-09T08:05:00Z', title: 'Auto-flagged for offensive language', actor: 'System' },
    ],
    createdAt: '2025-04-09T08:05:00Z',
    updatedAt: '2025-04-09T08:05:00Z',
    notes: [],
  },
];

export default userIncidents;
