const verifications = [
  { id: 'ver-001', userId: 'user-007', userName: 'Roberto Lim', userRole: 'contractor', type: 'government_id', status: 'pending', submittedAt: '2025-05-02T08:00:00Z', documents: [{ name: 'Driver License Front', type: 'image/jpeg' }, { name: 'Driver License Back', type: 'image/jpeg' }, { name: 'Selfie with ID', type: 'image/jpeg' }], reviewerId: null, remarks: '', reviewedAt: null },
  { id: 'ver-002', userId: 'user-013', userName: 'Emilio Aguilar', userRole: 'talent', type: 'government_id', status: 'pending', submittedAt: '2025-05-16T10:00:00Z', documents: [{ name: 'Passport Page', type: 'image/png' }, { name: 'Selfie', type: 'image/jpeg' }], reviewerId: null, remarks: '', reviewedAt: null },
  { id: 'ver-003', userId: 'user-006', userName: 'Elena Villanueva', userRole: 'client', type: 'government_id', status: 'approved', submittedAt: '2025-04-11T11:00:00Z', documents: [{ name: 'UMID Front', type: 'image/jpeg' }, { name: 'UMID Back', type: 'image/jpeg' }], reviewerId: 'admin-001', remarks: 'Documents verified. ID matches provided details.', reviewedAt: '2025-04-12T14:00:00Z' },
  { id: 'ver-004', userId: 'user-010', userName: 'Sofia Ramirez', userRole: 'client', type: 'government_id', status: 'rejected', submittedAt: '2025-03-11T12:00:00Z', documents: [{ name: 'Driver License Front', type: 'image/jpeg' }, { name: 'Driver License Back', type: 'image/jpeg' }], reviewerId: 'admin-001', remarks: 'Documents appear tampered. Name mismatch with account.', reviewedAt: '2025-03-12T09:00:00Z' },
  { id: 'ver-005', userId: 'user-002', userName: 'Maria Santos', userRole: 'talent', type: 'government_id', status: 'approved', submittedAt: '2024-02-21T10:30:00Z', documents: [{ name: 'National ID Front', type: 'image/jpeg' }, { name: 'National ID Back', type: 'image/jpeg' }], reviewerId: 'admin-001', remarks: 'Verified.', reviewedAt: '2024-02-22T08:00:00Z' },
  { id: 'ver-006', userId: 'user-005', userName: 'Carlos Mendoza', userRole: 'talent', type: 'government_id', status: 'approved', submittedAt: '2024-02-02T07:45:00Z', documents: [{ name: 'Driver License', type: 'image/jpeg' }, { name: 'Selfie', type: 'image/jpeg' }], reviewerId: 'admin-001', remarks: 'Verified', reviewedAt: '2024-02-03T09:00:00Z' },
  { id: 'ver-007', userId: 'user-011', userName: 'Jose Rizal III', userRole: 'contractor', type: 'government_id', status: 'approved', submittedAt: '2024-05-02T07:00:00Z', documents: [{ name: 'Passport', type: 'image/jpeg' }, { name: 'Professional License', type: 'image/jpeg' }], reviewerId: 'admin-001', remarks: 'All documents verified.', reviewedAt: '2024-05-03T10:00:00Z' },
  { id: 'ver-008', userId: 'user-004', userName: 'Ana Gonzales', userRole: 'equipment_owner', type: 'government_id', status: 'approved', submittedAt: '2024-03-06T09:00:00Z', documents: [{ name: 'UMID', type: 'image/jpeg' }], reviewerId: 'admin-001', remarks: 'Verified', reviewedAt: '2024-03-07T08:30:00Z' },
  { id: 'ver-009', userId: 'user-009', userName: 'Antonio Flores', userRole: 'talent', type: 'government_id', status: 'approved', submittedAt: '2024-01-21T09:30:00Z', documents: [{ name: 'National ID', type: 'image/jpeg' }], reviewerId: 'admin-001', remarks: 'Verified', reviewedAt: '2024-01-22T10:00:00Z' },
  { id: 'ver-010', userId: 'user-015', userName: 'Fernando Santiago', userRole: 'talent', type: 'government_id', status: 'approved', submittedAt: '2024-02-11T06:00:00Z', documents: [{ name: 'Driver License', type: 'image/jpeg' }], reviewerId: 'admin-001', remarks: 'Verified', reviewedAt: '2024-02-12T07:00:00Z' },
];

export default verifications;
